### ISSUE TITLE
Provide appimage

### ISSUE THREAD

**Issue by cweiske** [mijorus/gearlever#208] opened 2024-12-16 09:23 UTC
It's kinda ironic that gearlever is only available as flatpak. I use app images because I don't want to use flatpaks, and now the app to manage appimages needs the flatpak infrastructure.

It would be nice if gearlever would be available as app image.

**Comment by lguenth** [comment] 2024-12-17 17:27
Likely duplicate of #186 and #83

**Closed** 2024-12-17 18:35 UTC
